Upgrade pip on Appveyor
Because pip 20.2.3 complains

    ERROR: '.[test]' is not a valid editable requirement. It should
    either be a path to a local project or a VCS URL (beginning with
    svn+, git+, hg+, or bzr+).
    WARNING: You are using pip version 20.2.3; however, version 24.0 is available.
    You should consider upgrading via the 'c:\python39\python.exe -m pip
    install --upgrade pip' command.

and pip 23/24 do not complain on my laptop.